export {default as SofaIcon} from './SofaIcon'
export {default as CustomIcon} from './CustomIcon'
export {default as BedroomIcon} from './BedroomIcon'
export {default as GarageIcon} from './GarageIcon'
export {default as KidsRoomIcon} from './KidsRoomIcon'
export {default as KitchenIcon } from './KitchenIcon'
export {default as OfficeIcon} from './OfficeIcon'
export {default as TvIcon} from './TvIcon'